OpulusProject/opulus-frontend

src/components/Cover/Cover.module.scss, src/pages/Login/Login.tsx
**08531a8d8599a452938c98f2c1e591c96523efa5**
- Removed logo after discussion w/ Fadba since the logo is already displayed on the top left
**daea3b144d87bb0069e4cce7ada6646a2e2b99ee**
- Added spacing between quote and author on the left pane
=> Fixes to Login Page

src/components/Navrail/Navrail.tsx
Added links to navrail
Updated the name of the arrays
=> Raf update navrail links

postcss.config.js, tsconfig.json
=> Restore postcss.config.js

src/pages/Login/Login.tsx
- Update login hook to redirect to the route in `ROUTES`
- Add nav to sign up page when clicking on button
=> Login Page Navigation

src/layouts/Auth/Auth.tsx, src/layouts/Dashboard/Dashboard.tsx
Protected route logic is causing some issues with some onboarding. Removing for now, will reintroduce later.
- Remove logic to re-reoute unauth users to login
=> Remove Protected Route Logic

.eslintrc.cjs, tailwind.config.js
Some breaking changes caused by the linter.
=> Fix Tailwind

src/components/ui/multi-step-form.tsx
Found a super helpful open-source multi-step form:
https://makerkit.dev/blog/tutorials/multi-step-forms-reactjs
Separating this from the onboarding PR for improved readability.
=> Multi-step Form

src/App.tsx, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/index.tsx
Was getting 404 when trying to navigate to Accounts page. Added the route to App.tsx and created a page folder.
=> Fix Accounts 404

src/hooks/user/useMe.tsx
- parse was failing since id was updated to string in be, update schema to match
=> Fix User Schema

src/App.tsx
- FINALLY added logic that protects some routes, and keeps some routes public.
note: if the user's access token expires but they're still on the Dashboard, they won't be booted to the login page.
=> Protected Routes

src/hooks/auth/useLogin.tsx, src/hooks/auth/useLogout.tsx
https://github.com/OpulusProject/opulus-backend/pull/16
=> Sessions Refactor

.eslintrc.cjs, .gitignore, .storybook/main.ts, .storybook/preview.ts, package-lock.json, package.json
=> Storybook Setup

.storybook/main.ts, package-lock.json, package.json, src/components/DistributionBar/DistributionBar.stories.tsx
Created a story for the `DistributionBar` component.
1. Run storybook and make sure the component shows up.
#35
=> Story for DistributionBar

src/components/DistributionBar/DistributionBar.tsx, src/components/DistributionBar/DistributionBarSegment.tsx
- Use interfaces instead of types
=> Distribution Bar Minor Changes

src/App.tsx, src/hooks/user/useCreateUser.tsx, src/hooks/user/useGetUser.tsx, src/pages/Overview/Overview.tsx, src/pages/Signup/Signup.tsx
Some of the changes in https://github.com/OpulusProject/opulus-backend/pull/18 introduce breaking changes as the endpoints for `getMe` have changed. This PR adds in the respective changes to the front end.
=> User Hooks Refactor

src/App.tsx
- Forcing dark mode, will need to build a toggle later.
=> Force Dark Mode

package-lock.json, package.json, src/components/LaunchLink/LaunchLink.tsx, src/hooks/item/useCreateItem.ts, src/hooks/item/useGetItem.ts, src/hooks/plaid/useLinkToken.tsx, src/pages/Accounts/Accounts.tsx
I integrated Plaid's `Link` component to allow users to link their institution to our application. This uses the changes from https://github.com/OpulusProject/opulus-backend/pull/19 to write data to our database. 
Note this PR cannot be merged until the back end PR is merged.
https://github.com/user-attachments/assets/86493c11-0cf7-4e4b-9fa5-670d20957568
1. You will need to have the `saf/create-items` branch running locally in your back end
=> Add Accounts Flow

src/components/Page/Page.stories.tsx, src/components/Page/Page.tsx, src/components/Page/PageContent.tsx, src/components/Page/PageDate.tsx, src/components/Page/PageHeader.tsx, src/components/Page/PageHeaderDate.tsx, src/components/Page/PageHeaderTitle.tsx, src/components/index.ts
- Created a page component
- run storybook
=> Page Component

.storybook/main.ts, .storybook/preview.ts, package-lock.json, package.json, src/components/custom/BalanceDisplay/BalanceDisplay.stories.tsx, src/components/custom/BalanceDisplay/BalanceDisplay.tsx, src/components/custom/Typography/Typography.tsx, src/components/custom/Typography/index.tsx, tailwind.config.js
Added the `BalanceDisplay` component. This is the same component as `AmountDisplay` from #54, separating into this PR since I need for the `AccountCard` component. 
Also added dark mode to storybook, so components can be visually tested in both themes.
=> BalanceDisplay Component

src/components/charts/LineChart/LineChart.stories.tsx, src/components/charts/LineChart/LineChart.tsx
- LineChart label was previously having issues with spacing when numbers were over 4 digits. Now fixed. 
- Also changed the story to use relative width instead of fixed.
=> Fix LineChart Label

.storybook/main.ts, .storybook/preview.ts, src/components/custom/Card/Card.stories.tsx, src/components/custom/Card/Card.tsx, src/components/custom/Card/CardContent.tsx, src/components/custom/Card/CardHeader.tsx, src/components/custom/Color/Color.tsx, src/components/custom/Glossary/GlossaryRowLabel.tsx, src/components/custom/Page/Page.tsx, src/components/custom/Page/PageContent.tsx, src/components/custom/Page/PageDate.tsx, src/components/custom/Page/PageHeader.tsx, src/index.css
- Cleaned up several components' styling:
1. Page 
2. Card
3. Color: circle was getting squished previously so specified an aspect ration it needs to retain
4. GlossaryRowLabel: corrected the text variant based on designs
- Added colors from Fadba's new dark mode list
=> Component Cleanup + Dark Mode Color Change
